CREATE TABLE FAVORITES(
posts_id VARCHAR(15),
user_id VARCHAR(11),
new_date DATETIME DEFAULT '2021-01-01' NOT NULL,
tags VARCHAR(500),
PRIMARY KEY(posts_id,user_id),
FOREIGN KEY(user_id) REFERENCES USERS(user_account) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(posts_id) REFERENCES POSTS(POSTS_ID) ON DELETE CASCADE ON UPDATE CASCADE
);