CREATE TABLE REPORT(  
##REPLY_id VARCHAR(15)PRIMARY KEY,
father_id VARCHAR(15),
times INT DEFAULT 1,
user_id VARCHAR(11), 
posts_new_date DATETIME DEFAULT '2021-01-01' NOT NULL,
report_article TINYTEXT,
TAGS VARCHAR(500),
PRIMARY KEY(father_id,times),
FOREIGN KEY(user_id) REFERENCES USERS(user_account) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(father_id) REFERENCES POSTS(posts_id) ON DELETE CASCADE ON UPDATE CASCADE 
);##TYPE =INNODB;##ENGINE INNODB;