CREATE TABLE thumbs_up(
posts_id VARCHAR(15),
user_id VARCHAR(11),
thumbs_up_new_date DATETIME DEFAULT '2021-01-01' NOT NULL,
PRIMARY KEY(posts_id,user_id),
FOREIGN KEY(user_id) REFERENCES USERS(user_account) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(posts_id) REFERENCES POSTS(posts_id) ON DELETE CASCADE ON UPDATE CASCADE
);