CREATE TABLE REPLY(  
##REPLY_id VARCHAR(15)PRIMARY KEY,
father_id VARCHAR(15),
floor INT DEFAULT 1,
user_id VARCHAR(11), 
reply_new_date DATETIME DEFAULT '2021-01-01' NOT NULL,
reply_article LONGTEXT,
likes_count INT,
PRIMARY KEY(father_id,floor),
FOREIGN KEY(user_id) REFERENCES USERS(user_account) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(father_id) REFERENCES POSTS(posts_id) ON DELETE CASCADE ON UPDATE CASCADE 
);##TYPE =INNODB;##ENGINE INNODB;