CREATE TABLE thumbs_up(
post_id BIGINT,
client_id BIGINT,
thumbs_up_new_date DATETIME DEFAULT '2021-01-01' NOT NULL,
PRIMARY KEY(post_id,client_id),
FOREIGN KEY(client_id) REFERENCES client(client_id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(post_id) REFERENCES POST(post_id) ON DELETE CASCADE ON UPDATE CASCADE
);