CREATE TABLE report(  
##REPLY_id VARCHAR(15)PRIMARY KEY,
father_id BIGINT,
times INT DEFAULT 1,
client_id BIGINT, 
post_new_date DATETIME DEFAULT '2021-01-01' NOT NULL,
report_article TINYTEXT,
tag VARCHAR(500),
PRIMARY KEY(father_id,times),
FOREIGN KEY(client_id) REFERENCES client(client_id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(father_id) REFERENCES post(post_id) ON DELETE CASCADE ON UPDATE CASCADE 
);##TYPE =INNODB;##ENGINE INNODB;