-- INSERT INTO post(post_id,client_id,post_article) VALUES(0,0,"root0rootroot0");
-- INSERT INTO post(post_id,client_id,post_article) VALUES(1,0,"root1rootroot0");
-- INSERT INTO post(post_id,client_id,post_article) VALUES(2,0,"root2rootroot0");
-- INSERT INTO post(post_id,client_id,post_article) VALUES(3,0,"root3rootroot0");
-- INSERT INTO post(post_id,client_id,post_article) VALUES(4,0,"root4rootroot0");
-- INSERT INTO post(post_id,client_id,post_article) VALUES(5,0,"root5rootroot0");
-- INSERT INTO post(post_id,client_id,post_article) VALUES(6,0,"root6rootroot0");
-- INSERT INTO post(post_id,client_id,post_article) VALUES(7,0,"root7rootroot0");

INSERT INTO `database4tilitili`.`post`(`post_id`, `client_id`, `post_new_date`, `post_title`, `post_article`, `thumbs_up_count`, `favorite_count`, `remark_count`) VALUES (162072492526107, 1, '2021-05-11 17:22:05', '99 child', 'fuck u all', NULL, NULL, NULL);
INSERT INTO `database4tilitili`.`post`(`post_id`, `client_id`, `post_new_date`, `post_title`, `post_article`, `thumbs_up_count`, `favorite_count`, `remark_count`) VALUES (162072451331009, 1, '2021-05-11 17:15:13', '233', '233233', NULL, NULL, NULL);
INSERT INTO `database4tilitili`.`post`(`post_id`, `client_id`, `post_new_date`, `post_title`, `post_article`, `thumbs_up_count`, `favorite_count`, `remark_count`) VALUES (162072414385205, 1, '2021-05-11 17:09:04', '23333', '33333', NULL, NULL, NULL);
INSERT INTO `database4tilitili`.`post`(`post_id`, `client_id`, `post_new_date`, `post_title`, `post_article`, `thumbs_up_count`, `favorite_count`, `remark_count`) VALUES (162072368463804, 1, '2021-05-11 17:01:25', 'edssdf', 'dsffsddf', NULL, NULL, NULL);
INSERT INTO `database4tilitili`.`post`(`post_id`, `client_id`, `post_new_date`, `post_title`, `post_article`, `thumbs_up_count`, `favorite_count`, `remark_count`) VALUES (162072360856809, 1, '2021-05-11 17:00:05', '213', '123', NULL, NULL, NULL);
INSERT INTO `database4tilitili`.`post`(`post_id`, `client_id`, `post_new_date`, `post_title`, `post_article`, `thumbs_up_count`, `favorite_count`, `remark_count`) VALUES (123, 1, '2021-01-01 00:00:00', 'vcfgsdgsdg', 'vcfgsdgsdgsdgdssdgsgsdgsd', NULL, NULL, NULL);
INSERT INTO `database4tilitili`.`post`(`post_id`, `client_id`, `post_new_date`, `post_title`, `post_article`, `thumbs_up_count`, `favorite_count`, `remark_count`) VALUES (8, 1, '2021-05-11 16:15:43', 'root8ro!', 'root8rootroot0', NULL, NULL, NULL);
INSERT INTO `database4tilitili`.`post`(`post_id`, `client_id`, `post_new_date`, `post_title`, `post_article`, `thumbs_up_count`, `favorite_count`, `remark_count`) VALUES (7, 0, '2021-05-11 16:04:02', 'root7rootr', 'root7rootroot0', NULL, NULL, NULL);
INSERT INTO `database4tilitili`.`post`(`post_id`, `client_id`, `post_new_date`, `post_title`, `post_article`, `thumbs_up_count`, `favorite_count`, `remark_count`) VALUES (6, 0, '2021-01-01 00:00:00', 'root6rootr', 'root6rootroot0', NULL, NULL, NULL);
INSERT INTO `database4tilitili`.`post`(`post_id`, `client_id`, `post_new_date`, `post_title`, `post_article`, `thumbs_up_count`, `favorite_count`, `remark_count`) VALUES (5, 0, '2021-01-01 00:00:00', 'root5rootr', 'root5rootroot0', NULL, NULL, NULL);
INSERT INTO `database4tilitili`.`post`(`post_id`, `client_id`, `post_new_date`, `post_title`, `post_article`, `thumbs_up_count`, `favorite_count`, `remark_count`) VALUES (4, 0, '2021-01-01 00:00:00', 'root4rootr', 'root4rootroot0', NULL, NULL, NULL);
INSERT INTO `database4tilitili`.`post`(`post_id`, `client_id`, `post_new_date`, `post_title`, `post_article`, `thumbs_up_count`, `favorite_count`, `remark_count`) VALUES (3, 0, '2021-01-01 00:00:00', 'root3rootr', 'root3rootroot0', NULL, NULL, NULL);
INSERT INTO `database4tilitili`.`post`(`post_id`, `client_id`, `post_new_date`, `post_title`, `post_article`, `thumbs_up_count`, `favorite_count`, `remark_count`) VALUES (2, 0, '2021-01-01 00:00:00', 'root2rootr', 'root2rootroot0', NULL, NULL, NULL);
INSERT INTO `database4tilitili`.`post`(`post_id`, `client_id`, `post_new_date`, `post_title`, `post_article`, `thumbs_up_count`, `favorite_count`, `remark_count`) VALUES (1, 0, '2021-01-01 00:00:00', 'root1rootr', 'root1rootroot0', NULL, NULL, NULL);
INSERT INTO `database4tilitili`.`post`(`post_id`, `client_id`, `post_new_date`, `post_title`, `post_article`, `thumbs_up_count`, `favorite_count`, `remark_count`) VALUES (0, 0, '2021-01-01 00:00:00', 'root0rootr', 'root0rootroot0', NULL, NULL, NULL);
